/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Enterprise {
    readonly id: number;
    name: string;
    tax_code: string;
    ceo: string;
    main_job: string;
    slogan?: string;
    business_license: string;
    office_address: string;
    license_date: string;
}
