/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Enterprise {
    readonly id: number;
    international_name: string;
    abbreviation: string;
    tax_code: string;
    address: string;
    ceo: string;
    phone: string;
    active_date: string;
    status: string;
    type_of_business: string;
    manager_by: string;
    view_company_online?: string;
}
