version: "3.8"
services:
  compaon-service:
    container_name: compaon-service
    image: compaon-service:latest
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./resources:/app/resources
    restart: unless-stopped
  mysql:
    image: mysql:5.7
    # For MAC M1
    # image: arm64v8/mysql:oracle
    container_name: compaon.mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --sql_mode=""
    volumes:
      - ./db_data/db:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
