openapi: 3.0.0
info:
  title: COMPAON PUBLIC API
  version: 1.0.0
  contact:
    email: compaon@dalavina.com
    name: Compaon
    url: 'https://dalavina.com/compaon'
  license:
    name: EULA
    url: 'https://en.wikipedia.org/wiki/End-user_license_agreement'
  description: API definition for COMPAON
tags:
  - name: Exhibition
    description: API to interact with the Exhibition
  - name: Media
    description: API to interact with the Media
servers:
  - url: 'http://52.74.156.150:3000/public/api/v1'
paths:
  '/exhibitions/{id}':
    parameters:
      - name: id
        description: ID to get exhibition
        in: path
        required: true
        schema:
          type: string
          pattern: '^[0-9]+$'
    get:
      summary: Get exhibition by ID
      description: Return a single exhibition
      operationId: getExhibitionById
      parameters:
        - in: query
          name: populate
          schema:
            type: array
            items:
              type: string
              example: 'category'
          description: |
            List of populatable columns:
            - booths
            - booths.booth_template
            - booths.location_status
            - booth_organization
            - booth_organization.booth_organization_data
            - booth_organization.booth_template
            - booth_organization.booth_template.position_booths
            - booth_templates
            - booth_templates.position_booths
            - category
            - space
            - space.space_template
            - space.space_datas
            - space.space_template.position_spaces
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exhibition'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
              examples:
                example-1:
                  value:
                    message: Bad Request
                    details:
                      - field: .params.id
                        message: 'should match pattern "^[0-9]+$"'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
              examples:
                example-1:
                  value:
                    message: Internal server error
                    details: []
      tags:
        - Exhibition
components:
  schemas:
    Exhibition:
      type: object
      required:
        - id
        - name
        - booth_number
        - exhibition_code
        - date_exhibition_start
        - date_exhibition_end
        - introduction
        - agenda
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          minLength: 1
          maxLength: 255
          example: Triển lãm xúc tiến đầu tư thương mại
        exhibition_code:
          type: string
          minLength: 1
          maxLength: 255
          pattern: '^[a-zA-Z0-9_-]+$'
          example: TL0001
        booth_number:
          type: integer
          example: 100
        date_exhibition_start:
          type: string
          minLength: 1
          pattern: '^[1-9]\d{3}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z$'
          example: '2022-01-01T00:00:00.000Z'
        date_exhibition_end:
          type: string
          minLength: 1
          pattern: '^[1-9]\d{3}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z$'
          example: '2022-12-01T00:00:00.000Z'
        introduction:
          type: string
          minLength: 1
          maxLength: 20000
          example: Giới thiệu công ty Tòa nhà C22-Officetel, số 22 Nguyễn Việt Hồng, phường An Phú, quận Ninh Kiều, TP. Cần Thơ
        agenda:
          type: string
          minLength: 1
          maxLength: 20000
          example: '07h45 - 08h20: Đón tiếp đại biểu, 08h20 - 08h40: Ca nhạc chào mừng'
        status:
          type: string
          enum: ['new', 'listing', 'finished']
          example: 'new'
        category:
          $ref: '#/components/schemas/Category'
        space:
          $ref: '#/components/schemas/Space'
        booth_templates:
          type: array
          items:
            $ref: '#/components/schemas/BoothTemplate'
        space_template:
          $ref: '#/components/schemas/SpaceTemplate'
        booth_organization:
          $ref: '#/components/schemas/BoothOrganization'
    Category:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          example: 0
          description: The number id category.
        name:
          type: string
          example: 'loai triễn lảm'
          description: The name category.
    BoothOrganization:
      type: object
      required:
        - id
        - booth_template_id
        - user_id
        - name
        - booth_organization_data
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        booth_template_id:
          type: integer
          example: 1
        user_id:
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          minLength: 1
          maxLength: 255
          example: Gian hàng ban tổ chức
        booth_organization_data:
          type: array
          items:
            $ref: '#/components/schemas/BoothOrganizationData'
    BoothOrganizationData:
      type: object
      required:
        - id
        - position_booth_id
      properties:
        id:
          type: integer
          readOnly: true
          example:
        position_booth_id:
          type: integer
          writeOnly: true
        position_booth:
          $ref: '#/components/schemas/PositionBooth'
        selected_media_id:
          type: integer
          writeOnly: true
        media_id:
          type: integer
          readOnly: true
        media_data:
          type: string
          writeOnly: true
        title:
          type: string
        description:
          type: string
          maxLength: 20000
    Space:
      type: object
      required:
        - id
        - space_template_id
        - name
        - space_datas
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        space_template:
          $ref: '#/components/schemas/SpaceTemplate'
        name:
          type: string
          minLength: 1
          maxLength: 255
          example: 'Mau khong gian tien sanh mac dinh'
        user_id:
          type: integer
          readOnly: true
          example: 1
        space_datas:
          type: array
          items:
            $ref: '#/components/schemas/SpaceData'
    SpaceData:
      type: object
      required:
        - id
        - position_space_id
        - media_id
      properties:
        id:
          type: integer
          readOnly: true
        position_space_id:
          type: integer
          writeOnly: true
        position_space:
          $ref: '#/components/schemas/PositionSpace'
        selected_media_id:
          type: integer
          writeOnly: true
        media_id:
          type: integer
          readOnly: true
        media_data:
          type: string
          writeOnly: true
        title:
          type: string
        description:
          type: string
    BoothTemplate:
      type: object
      required:
        - id
        - model_data
        - thumbnail_data
        - name
        - type
        - created_by
        - created_date
        - model_id
        - thumbnail_id
        - position_booths
      properties:
        id:
          type: integer
          readOnly: true
        created_by:
          type: integer
          readOnly: true
        created_date:
          type: string
          readOnly: true
        model_data:
          type: string
          description: 'input base64 string /n example: iVBORw0KGgoAAAANSUhEUgAABuIAAASxCAYAAADF8I...'
          writeOnly: true
        thumbnail_data:
          type: string
          description: "input base64 string example: iVBORw0KGgoAAAANSUhEUgAABuIAAASxCAYAAADF8I..."
          writeOnly: true
        name:
          type: string
          minLength: 1
          maxLength: 255
        type:
          type: string
          enum: ['project', 'product', 'organize']
          example: 'project'
        model_id:
          type: integer
          readOnly: true
        thumbnail_id:
          type: integer
          readOnly: true
        position_booths:
          writeOnly: true
          type: array
          items:
            $ref: '#/components/schemas/PositionBooth'
    PositionBooth:
      type: object
      required:
        - id
        - type
        - object_3d_id
      properties:
        id:
          type: number
          readOnly: true
          example: 1
        type:
          type: string
          example: 'img'
        object_3d_id:
          type: string
          pattern: '^[a-zA-Z\d\-_.,\s]+$'
          maxLength: 255
    SpaceTemplate:
      type: object
      required:
        - id
        - name
        - model_id
        - thumbnail_id
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          minLength: 1
          maxLength: 255
        model_id:
          type: integer
          readOnly: true
        thumbnail_id:
          type: integer
          readOnly: true
        exhibition_map_id:
          type: integer
          readOnly: true
        position_spaces:
          type: array
          items:
            $ref: '#/components/schemas/PositionSpace'
        spaces:
          type: array
          items:
            $ref: '#/components/schemas/Space'
    PositionSpace:
      type: object
      readOnly: true
      required:
       - id
       - object_3d_id
       - type
      properties:
        id:
          type: integer
          readOnly: true
        object_3d_id:
          type: string
          pattern: '^[a-zA-Z\d\-_.,\s]+$'
          maxLength: 255
        type:
          type: string
          description: "input value [image, video, text]"
          minLength: 1
          maxLength: 255
    ErrorResponseBody:
      type: object
      required:
        - message
        - details
      properties:
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
    ErrorDetail:
      type: object
      required:
        - field
        - message
      properties:
        field:
          type: string
        message:
          type: string
    BoothData:
      type: object
      required:
        - id
        - position_booth_id
        - media_id
      properties:
        id:
          type: integer
          readOnly: true
        position_booth_id:
          type: integer
          writeOnly: true
        selected_media_id:
          type: integer
          writeOnly: true
        media_id:
          type: integer
          readOnly: true
        media_data:
          type: string
          writeOnly: true
    Project:
      type: object
      required:
        - id
        - position_booth_id
        - media_id
        - title
        - description
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        position_booth_id:
          type: integer
          writeOnly: true
        selected_media_id:
          type: integer
          writeOnly: true
        media_id:
          type: integer
          readOnly: true
        media_data:
          type: string
          writeOnly: true
        title:
          type: string
        description:
          type: string
          maxLength: 20000
    Product:
      type: object
      required:
        - id
        - name
        - price
        - purchase_link
        - position_booth_id
        - description
        - media_id
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        position_booth_id:
          type: integer
          writeOnly: true
        selected_media_id:
          type: integer
          writeOnly: true
        media_id:
          type: integer
          readOnly: true
        media_data:
          type: string
          writeOnly: true
        name:
          type: string
        price:
          type: integer
        purchase_link:
          type: string
        description:
          type: string
          maxLength: 20000
    LiveStream:
      type: object
      required:
        - id
        - link
        - date
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        link:
          type: string
          minLength: 1
          example: 'www.goole.com'
        date:
          type: string
          minLength: 1
          pattern: '^[1-9]\d{3}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z$'
          example: '2022-12-01T00:00:00.000Z'
    Booth:
      type: object
      required:
        - id
        - name
        - enterprise_id
        - created_by
        - location_status_id
        - booth_template_id
        - booth_data
        - live_streams
      properties:
        id:
          type: integer
          example: 1
          description: The number id booth.
          readOnly: true
        name:
          type: string
          example: 'triễn lảm'
          description: The name category.
        enterprise_id:
          type: integer
          example: 1
        created_by:
          type: integer
          readOnly: true
          example: 1
        location_status_id:
          type: integer
          writeOnly: true
          example: 1
        booth_template_id:
          type: integer
          writeOnly: true
          example: 1
        live_streams:
          type: array
          items:
            $ref: '#/components/schemas/LiveStream'
        booth_data:
          type: array
          items:
            $ref: '#/components/schemas/BoothData'
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
