/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BoothOrganizationTemplatePosition } from './booth-organization-template-position.dto';

export interface BoothOrganizationTemplate {
    readonly id: number;
    name: string;
    readonly created_by: number;
    readonly created_date: string;
    readonly model_id: number;
    readonly thumbnail_id: number;
    model_data?: string;
    thumbnail_data?: string;
    booth_organization_template_positions?: Array<BoothOrganizationTemplatePosition>;
}
