/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type } from '@/components/exhibition/entities/booth-organization-template-position.entity';

export interface BoothOrganizationTemplatePosition {
    readonly id: number;
    position: string;
    type: Type;
}
