/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoothOrganizationProject } from './booth-organization-project.dto';
import { BoothOrganizationVideo } from './booth-organization-video.dto';
import { BoothOrganizationImage } from './booth-organization-image.dto';
import { BoothOrganizationProduct } from './booth-organization-product.dto';
import { BoothOrganizationTemplate } from './booth-organization-template.dto';

export interface BoothOrganization {
    readonly id: number;
    position_x?: number;
    position_y?: number;
    position_z?: number;
    rotation_x?: number;
    rotation_y?: number;
    rotation_z?: number;
    booth_organization_template_id?: number;
    booth_organization_template?: BoothOrganizationTemplate;
    booth_organization_images?: Array<BoothOrganizationImage>;
    booth_organization_videos?: Array<BoothOrganizationVideo>;
    booth_organization_projects?: Array<BoothOrganizationProject>;
    booth_organization_products?: Array<BoothOrganizationProduct>;
}
