/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardBoothTemplates } from './dashboard-booth-templates.dto';
import { DashboardEnterprises } from './dashboard-enterprises.dto';
import { DashboardExhibitions } from './dashboard-exhibitions.dto';
import { DashboardViewerOfExhibitions } from './dashboard-viewer-of-exhibitions.dto';
import { StatisticOfExhibitions } from './statistic-of-exhibitions.dto';

export interface Dashboard {
    max_view_exhibition: number;
    total_viewer: number;
    viewer_of_exhibitions: Array<DashboardViewerOfExhibitions>;
    enterprises: Array<DashboardEnterprises>;
    booth_templates: Array<DashboardBoothTemplates>;
    exhibitions: DashboardExhibitions;
    statistic_of_exhibitions: Array<StatisticOfExhibitions>;
    total_livestream: number;
    total_meeting: number;
}
