/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Status } from '../entities/exhibition.entity';
import { BoothOrganization } from './booth-organization.dto';
import { Category } from './category.dto';
import { Space } from './space.dto';

export interface Exhibition {
    readonly id: number;
    name: string;
    booth_number: number;
    exhibition_code: string;
    date_exhibition_start: string;
    date_exhibition_end: string;
    introduction: string;
    agenda: string;
    status: Status;
    category_id: number;
    readonly booth_organization_id?: number;
    readonly space_id?: number;
    space_template_id: number;
    booth_organization_template_id: number;
    category?: Category;
    space?: Space;
    booth_organization?: BoothOrganization;
}
