/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Location {
    readonly id: number;
    name: string;
    position_x: string;
    position_y: string;
    position_z: string;
    rotation_x: string;
    rotation_y: string;
    rotation_z: string;
}
