/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpaceTemplateLocation } from './space-template-location.dto';

export interface Location {
    readonly id: number;
    status: Status;
    space_id: number;
    space_template_location_id: number;
    readonly space_template_location?: SpaceTemplateLocation;
}
export enum Status {
    AVAILABLE = 'available',
    RESERVED = 'reserved',
}
