/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SpaceTemplateLocation } from './space-template-location.dto';

export interface Location {
    readonly id: number;
    status: string;
    space_template_location: SpaceTemplateLocation;
}
