/**
 * COMPAON PUBLIC API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Booth } from './booth.dto';

export interface Meeting {
    readonly id: number;
    booth_id: number;
    customer_name: string;
    phone: string;
    email: string;
    start_time: string;
    end_time: string;
    note?: string;
    booth?: Booth;
}
