/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpaceTemplate } from './space-template.dto';

export interface PaginatedSpaceTemplates {
    page: number;
    limit: number;
    total: number;
    space_templates: Array<SpaceTemplate>;
}
