/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Booth } from './booth.dto';

export interface PaginatedBooths {
    readonly page: number;
    readonly limit: number;
    readonly total: number;
    booths: Array<Booth>;
}
