/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Registration } from './registration.dto';

export interface PaginatedRegistrations {
    readonly page: number;
    readonly limit: number;
    readonly total: number;
    registrations: Array<Registration>;
}
