/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export enum Status {
    NEW = 'new',
    ACCEPTED = 'accepted',
    REFUSED = 'refused',
}

export interface Registration {
    readonly id: number;
    name: string;
    phone: string;
    address: string;
    email: string;
    note?: string;
    status: Status;
    exhibition_id: number;
}
