/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Space } from './space.dto';
import { PositionSpace } from './position-space.dto';

export interface SpaceTemplate {
    readonly id: number;
    name: string;
    readonly model_id: number;
    readonly thumbnail_id: number;
    readonly exhibition_map_id?: number;
    position_spaces?: Array<PositionSpace>;
    spaces?: Array<Space>;
}
