/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Space } from './space.dto';
import { SpaceTemplatePosition } from './space-template-position.dto';

export interface SpaceTemplate {
    readonly id: number;
    name: string;
    readonly created_by: number;
    readonly model_id: number;
    readonly thumbnail_id: number;
    readonly map_id?: number;
    created_date: string;
    space_template_positions?: Array<SpaceTemplatePosition>;
    spaces?: Array<Space>;
}
