/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpaceVideo } from './space-video.dto';
import { SpaceImage } from './space-image.dto';
import { Location } from './location.dto';

export interface Space {
    readonly id: number;
    space_template_id?: number;
    name: string;
    exhibition_id: number;
    locations?: Array<Location>;
    space_images?: Array<SpaceImage>;
    space_videos?: Array<SpaceVideo>;
}
