/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role.dto';

export interface User {
    readonly id: number;
    phone: string;
    email: string;
    password: string;
    role_id: number;
    role?: Role;
    status: User.StatusEnum;
}
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace User {
    export type StatusEnum = 'active' | 'inactive';
    export const StatusEnum = {
        Active: 'active' as StatusEnum,
        Inactive: 'inactive' as StatusEnum,
    };
}
