/* tslint:disable */
/* eslint-disable */
/**
 * COMPAON API
 * API definition for COMPAON
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: compaon@dalavina.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorDetail } from './error-detail.dto';

/**
 *
 * @export
 * @interface ErrorResponseBody
 */
export interface ErrorResponseBody {
    /**
     *
     * @type {string}
     * @memberof ErrorResponseBody
     */
    message: string;
    /**
     *
     * @type {Array<ErrorDetail>}
     * @memberof ErrorResponseBody
     */
    details: Array<ErrorDetail>;
}
